### ISSUE TITLE
Use GitHub API to get latest release

### ISSUE THREAD

**Issue by 1138-4EB** [mviereck/x11docker#116]
In https://github.com/mviereck/x11docker/blob/master/x11docker#L1092-L1093 a file is downloaded from `master` ([CHANGELOG.md](https://github.com/mviereck/x11docker/blob/master/CHANGELOG.md)) and it is parsed in order to find the tag of the latest release, which is the one downloaded in zip format as commented in #115.

This is the current parsing procedure:

``` bash
curl -fsSL "https://raw.githubusercontent.com/mviereck/x11docker/master/CHANGELOG.md" | grep "## \[" | grep -v 'Unreleased' | head -n1 | cut -d[ -f2 | cut -d] -f1
```

I might be improved by using the GitHub API directly. A JSON file is returned, which can be parsed more easily because it contains a field with the expected data:

``` bash
curl -s https://api.github.com/repos/mviereck/x11docker/releases/latest | grep "\"name" | sed 's/.* "\(.*\)",/\1/g'
```

The benefits of this approach are:

- The JSON is expected to be smaller than `CHANGELOG.md`.
- The API should be stable, so the format of `CHANGELOG.md` can be changed without breaking the query.

I think that the rate limit applies to both of them, so there is no improvement in this sense.

**Comment by mviereck** [comment]
I'll keep parsing `CHANGELOG.md`. It follows [Keep a changelog](http://keepachangelog.com/en/1.0.0/) and is intended to be parseable.
The Github API is specific to Github and I don't want to depend on it.

In fact, I consider to move x11docker to [Gitlab](https://gitlab.com/users/sign_in) due to Microsofts's takeover of Github.
