### ISSUE TITLE
docker-for-win: containerized xpra server with xwin (cygwin)

### ISSUE THREAD

**Issue by 1138-4EB** [mviereck/x11docker#122]
Now that #120 is fixed, I can execute ` ./x11docker --gpu --user=root --cap-default -- -p "8080:8080" -- x11docker/xpra sh -c "apk add xterm && xterm"` in Cygwin, which will default to `--xwin`. The X server is properly started, and xterm is shown on the host. Then, from an MSYS terminal, I can:

``` bash
# winpty docker exec -it x11docker_X100_f3a77004f3d1e690a1d0c13362c4088c_x11docker-xpra sh
/tmp # xpra start $DISPLAY --use-display --bind-tcp=0.0.0.0:8080 --webcam=no --mdns=no --notifications=no --dbus-proxy=no --dbus-launch=no --pulseaudio=no

Warning: running as root
/tmp # Entering daemon mode; any further errors will be reported to:
  /tmp/10.0.75.1:100.log
cat /tmp/10.0.75.1:100.log
2019-02-03 00:58:38,230 Error: cannot enable SSH socket upgrades:
2019-02-03 00:58:38,231  No module named paramiko
error running (['xprop', '-display', '10.0.75.1:100', '-root', '_XPRA_UINPUT_ID'],),{'stderr': -1, 'stdout': -1}: [Errno 2] No such fi
le or directory
2019-02-03 00:58:38,306 Warning: failed to create socket directory '/run/user/0/xpra'
2019-02-03 00:58:38,306  [Errno 2] No such file or directory: '/run/user/0/xpra'
2019-02-03 00:58:38,306 Warning: cannot create socket '/run/user/0/xpra/b59bbb2a99c7-10.0.75.1:100':
2019-02-03 00:58:38,306  [Errno 2] No such file or directory
2019-02-03 00:58:38,306  /run/user does not exist
2019-02-03 00:58:38,306 created unix domain socket: /run/xpra/b59bbb2a99c7-10.0.75.1:100
2019-02-03 00:58:38,313 Warning: no XShm support on display 10.0.75.1:100
2019-02-03 00:58:38,349 pointer device emulation using XTest
2019-02-03 00:58:38,350 Warning: XTest extension is missing
2019-02-03 00:58:38,350 Error: keyboard and mouse disabled
2019-02-03 00:58:38,838  OpenGL is supported on this display
2019-02-03 00:58:38,971 html server unavailable, cannot find websockify module

Warning: running as root
Warning: failed to import GStreamer 1.x:
 No module named gi
2019-02-03 00:58:39,292 Error: failed to query sound subsystem:
2019-02-03 00:58:39,292  query did not return any data
2019-02-03 00:58:39,561 xpra X11 version 2.4.2-r21077 64-bit
2019-02-03 00:58:39,562  uid=0, gid=0
2019-02-03 00:58:39,562  running with pid 103 on Linux
2019-02-03 00:58:39,660 xpra is ready.
2019-02-03 00:58:39,674 7.8GB of system memory
```

The xterm windows disappears, and a huge window is opened on the host with title `Xpra-WorldWindow@b59bbb2a99c7`. With *huge* I mean that it takes all my desktop (two monitors).

When I connect with a xpra client (from the host), I see the xterm window again. So, at first sight it seems to work somehow. But there is an annoying issue and it is not really usable:

- Two xterm windows are shown, one below the other:
 - One is created by the xpra client (the xpra logo is shown) with title `xterm on 977b1caccd88`. The content (video/render) of xterm is shown here.
 - The other one is created by Xwin (the xwin logo is shown), with title `Xpra-CorralWindows-0x80000d`. It is just a black window with a title.

The annoyance is that keyboard input only works in the Xwin (black) window, which is behind. So, I need to select the black window from the taskbar and move it to a side. Then, I click inside and whatever I write there is shown in the other window. However, if I move the Xpra window, the Xwin one is positioned behind. See screencast below:

![xpra_xwin](https://user-images.githubusercontent.com/6628437/52171406-dffec100-275c-11e9-9b16-1ec1875b0c21.gif)

> NOTE: is the background is rendering strange (white/gray), ignore it. That's either some *optimization* that the recorder tried to do when generating the gif, or the browser when rendering it. 

---

For the record, I tried the same exercise with `--vcxsrv`. The result is the same as with MSYS2 (reported in [#117](https://github.com/mviereck/x11docker/issues/117#issuecomment-459963912)): xpra cannot start and vcxsrv takes 30% of the CPU and ceases to respond. I did add ` +extension COMPOSITE` manually.

---

@totaam, can this be related to you comment. *always try to avoid doing things this way* in [#117](https://github.com/mviereck/x11docker/issues/117#issuecomment-459608749)?

**EDIT**

When I disconnect the xpra client, the xterm window is closed, but `Xpra-CorralWindow` remains. When I close it, xpra terminates with `Xpra: Fatal IO error 11 (Resource temporarily unavailable) on X server 10.0.75.1:100.`, the huge window is closed and the xterm is shown again (because control is returned to xwin).

It seems that both the huge window and `Xpra-CorralWindow` should not be shown in the windows taskbar, and they should be permanently minimized.

**Comment by mviereck** [comment]
Quite interesting that Xwin works with xpra so far. x11docker command line setup for Xwin and VcXsrv is the same (including X over IP with IP:DISPLAY).

> The annoyance is that keyboard input only works in the Xwin (black) window, which is behind.
> 2019-02-03 00:58:38,350 Warning: XTest extension is missing

xpra needs extension `XTEST` for mouse and keyboard control, but x11docker disables it.
Look at line 2576ff: `  # X extension XTEST`. Just insert `Xtest=yes` and this will work. 
(Once x11docker had an option `--xtest` to manually enable/disable it. I dropped it because I thought no one would ever need it.)

> The xterm windows disappears, and a huge window is opened on the host with title Xpra-WorldWindow@b59bbb2a99c7. With huge I mean that it takes all my desktop (two monitors).

This is probably the root/background window xpra works with. Normally it is invisible (Xvfb/Xdummy), as well as the black application window.

> It seems that both the huge window and Xpra-CorralWindow should not be shown in the windows taskbar, and they should be permanently minimized.

I don't know how windows can be minimized/hidden on MS Windows. Linux provides e.g. `xdotool`, maybe Windows provides something similar.

**Comment by totaam** [comment]
> xpra needs extension XTEST

Yes.

> ... a huge window is opened on the host with title Xpra-WorldWindow@b59bbb2a99c7

The world window is meant to cover the whole desktop and is used for managing focus events.
You may be able to get by without it, we already do that for the python3 version of the server.
(comment it out in wm.py)

Each regular (non-OR) window will have a corral window reparenting it. Which means that the application window should always be shown inside the corral window.

> I don't know how windows can be minimized/hidden on MS Windows. Linux provides e.g. xdotool, maybe Windows provides something similar.

Normal window managers place decorations on their equivalent to the corral window: that's where the top bar and the minimize / maximize / close buttons live.
Xpra has no need for such things since users aren't meant to see the corral window..

**Comment by 1138-4EB** [comment]
> Maybe this will help:
> http://xpra.org/trac/changeset/21528
> http://xpra.org/trac/changeset/21529

Is there any info about the CI flow you use? Is it public?

I can build the latest from sources in a Debian container. However, I'll need some time to have it done on Windows. Anyway, those changes should only affect the server, so I'll try.
 
> In 2.5 it is almost ready.

Does it mean that I can install xpra 2.5 in a container without python2 at all, although with some bugs/missing features?

> They are not meant to be manipulated externally. They are not meant to be seen either.

I was wondering if I could issue a `minimize` command with `xdotool`, which would *hide* them. The only remaining thing would be to remove the icons from the task bar. However, I don't know if being minimized disables their functionaly, or if they keep working anyway.

> > How does xpra set the corral window not to be visible?
> 
> It doesn't!

Then, I'm missing something. How is it that two windows are created, one of them is not supposed to be visible, but xpra does not tell it explicitly? Is it because xpra ensures that the corral window is always behind the real window?

I'm trying to guess that, on GNU/Linux, the X server does not provide to the window manager the list of windows to be shown in `Alt+Tab`. It just displays them and some other mechanism is used to identify the *real* ones.

**Comment by mviereck** [comment]
> Does it mean that I can install xpra 2.5 in a container without python2 at all, although with some bugs/missing features?

Yesterday I've installed xpra with python3 on debian buster. It seems to work well so far.
I am using the xpra/winswitch repository for debian. Install package `python3-xpra` instead of package `xpra`.
```
$ xpra --version
xpra for python 2.7 is not installed
 retrying with python3
xpra v2.5-r21480
```
> I was wondering if I could issue a minimize command with xdotool, which would hide them. The only remaining thing would be to remove the icons from the task bar.

We can try to hide the windows with xdotool. However, I would prefer a `-hide` option in the X server that also disables task bar icons.

> However, I don't know if being minimized disables their functionaly, or if they keep working anyway.

A similar setup by x11docker is used with `--xpra-xwayland`. The weston window with Xwayland is hidden with `xdotool` but keeps working. xpra shows its content.

> How is it that two windows are created, one of them is not supposed to be visible, but xpra does not tell it explicitly?

Normally xpra uses Xvfb or Xdummy. They are always invisible (Xvfb = X virtual frame buffer), so xpra does not need to hide anything.

**Comment by mviereck** [comment]
Feel free to re-open if this is of interest again.
