### ISSUE TITLE
it is possible to modify portainer to start and stop x11docker from web gui?

### ISSUE THREAD

**Issue by lpt2007** [mviereck/x11docker#129]
I found this on web http://flat.wednus.com/ and I am wondering if it possible to modify portainer for x11docker so I can start and stop and modify x11docker apps from web gui?

**Comment by 1138-4EB** [comment]
It is technically possible. However, on the one hand, some parts of portainer are neither open source nor free software. So, you might need to contact the maintainers/developers or even pay for support. On the other hand, this issue is about portainer supporting x11docker, not the other way. Hence, I think that the question should be posed in [portainer/portainer](https://github.com/portainer/portainer).

**Comment by lpt2007** [comment]
Ok. Maybe there is another open source software we can use to control x11docker like [home assistant](https://www.home-assistant.io/) and [node-red](https://flows.nodered.org/node/node-red-contrib-docker-stream)?

**Comment by mviereck** [comment]
Every remote access that can execute terminal commands can be used to control x11docker remotely, e.g. `ssh`. The usage of such applications is not part of x11docker. Consult the documentation of this applications on how to use them.
