### ISSUE TITLE
Mac OS support

### ISSUE THREAD

**Issue by ACAVJW4H** [mviereck/x11docker#170]
Hey, I am aware of the previous issues and your answers on Mac OS support. Can this new repo https://github.com/foxlet/macOS-Simple-KVM change your mind on the subject?

**Comment by mviereck** [comment]
That is an interesting project, thank you for the link!

But I won't develop for macOS. 
Three points:
 - There is still no official free developer edition.
 - I already have trouble to keep x11docker running on MS Windows. It costs a lot of bugfixing effort for a minority of users. Currently I am reducing x11docker features on MS Windows to make things easier. If I add support for macOS, I get a lot of additional work for another minority of users.
 - macOS is a non-free system. That goes as well for MS Windows, though. I still keep support on MS Windows because I claimed MS Windows support at [JOSS](https://doi.org/10.21105/joss.01349). However, with the release of WSL2 I might reduce support on MS Windows for WSL2 only.

I recommend to run x11docker on a native Linux system. On macOS it it possible to use a Linux VM.
