### ISSUE TITLE
Is kde plasma still supported? 

### ISSUE THREAD

**Issue by springzfx** [mviereck/x11docker#183]
x11docker/plasma is not found on docker hub.

**Comment by mviereck** [comment]
In general KDE should still work.
The image `x11docker/plasma` has been pulled only few times, but caused a lot of work in maintaing, so I decided to drop it.

There is an image [`kdeneon/plasma`](https://hub.docker.com/r/kdeneon/plasma) that should work.

**Comment by springzfx** [comment]
I tried `kdeneon/plasma` , but it ends to black screen after showing kde logo.  Any idea why?

**Comment by mviereck** [comment]
I did some tests, too.

I could reproduce an all black screen with `--nxagent`, I'll investigate.
It works with `--xephyr`, `--weston-xwayland` and `--xorg`.

Please install e.g. `Xephyr` and try again. If you still have issues, please provide the logfile `~/.cache/x11docker/x11docker.log` at www.pastebin.com .

----------------------
`kdeneon/plasma` has an annoying `bluez` issue that did not get fixed since years: The bluetooth service fails to start and automatically restarts without a delay. That causes high CPU usage for no good reason. https://github.com/jriddell/kdeneon-docker/issues/1
It gives repeating error messages:
```
bluedevil: ObexManager operational changed false
bluedevil: ObexManager operational changed false
bluedevil: ObexManager operational changed false
bluedevil: ObexManager operational changed false
bluedevil: ObexManager operational changed false
```

You can avoid this issue with `--init=systemd`.
Example:
```
x11docker --desktop --init=systemd -- kdeneon/plasma:user-lts
```

**Comment by springzfx** [comment]
oh, yeah, it works. Thanks.

**Comment by mviereck** [comment]
> oh, yeah, it works. Thanks.

Good. :)
You might also want option `--gpu` to accelerate the desktop effects.  
That would need `weston`, `Xwayland` and `xdotool`.

**Comment by mviereck** [comment]
I've created a new x11docker/plasma Dockerfile:
```
FROM debian:buster

ENV LANG=en_US.UTF-8
RUN apt-get update && \
    env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      locales && \
    echo "$LANG UTF-8" >> /etc/locale.gen && \
    locale-gen && \
    env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      kwin-x11 \
      plasma-desktop \
      plasma-workspace && \
    apt-get remove -y bluedevil && \
    apt-get autoremove -y

# Dirty fix to avoid kdeinit error. Did not find a proper solution.
RUN sed -i 's/.*kdeinit/###&/' /usr/bin/startkde

RUN env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      konsole \
      kwrite \
      libcups2 \
      libpulse0 \
      procps \
      psmisc \
      sudo \
      synaptic \
      systemsettings

CMD startkde
```
It does not have the issues of `kdeneon/plasma` and is much smaller (about 1.2 GB compared to 2.5 GB).
It contains a dirty fix to avoid a startup failure with `kdeinit5`.

**Comment by mviereck** [comment]
I have created a new KDE Plasma repository: https://github.com/mviereck/dockerfile-x11docker-kde-plasma
Image on Docker hub: https://cloud.docker.com/repository/docker/x11docker/kde-plasma

It does not have the issues of `kdeneon/plasma` and additionally supports Wayland setups.
