### ISSUE TITLE
RFE: Custom shell for container user

### ISSUE THREAD

**Issue by seandilda** [mviereck/x11docker#211]
Would it be possible to add an option specifying what shell is added in /etc/passwd for the new container user?   I'm using x11docker to launch a different terminal, but I end up stuck with /bin/sh as my shell.  It'd be wonderful if I could pass a path on the command line to use instead.

**Comment by mviereck** [comment]
In my tests I found that environment variable `SHELL` supersedes the setting in `/etc/passwd`. It should work if you set e.g. `--env SHELL=/bin/zsh`.

x11docker sets `SHELL=/bin/bash` if available, otherwise it sets `SHELL=/bin/sh`. https://github.com/mviereck/x11docker/blob/master/x11docker#L5488

Please try out if that works for you.

**Comment by seandilda** [comment]
When I use xterm, I see the behavior you describe.  When I use terminator, the $SHELL value is ignored and /etc/passwd is used instead.

terminator does allow me to specify an alternative shell, so I do have a workaround.  However, I thought it might be a generally useful feature to allow an alternative shell for the container.

**Comment by mviereck** [comment]
> When I use xterm, I see the behavior you describe. When I use terminator, the $SHELL value is ignored and /etc/passwd is used instead.

Indeed, I can confirm that. 
I checked `xfce4-terminal`, it ignores `SHELL`, too. `gnome-terminal` regards it. This seems to be inconsistent across several terminals.

I once rejected a pull request  for this: https://github.com/mviereck/x11docker/pull/26
I wanted to avoid a growing number of options. Now I consider to add a `--shell` option because setting `SHELL` does not work reliable.

Imho terminals should regard `SHELL` and should get a bug report if they don't.
[POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html#tag_08_03) says:
> SHELL
    This variable shall represent a pathname of the user's preferred command language interpreter.

**Comment by mviereck** [comment]
I've added a new option `--shell`. Something like `--shell=/bin/zsh` should work now.
If your preferred shell is bash and has been set wrong by terminator before, it should be set automatically now without the need of `--shell`.

**Comment by seandilda** [comment]
Thanks!
