### ISSUE TITLE
Support for mobaxterm

### ISSUE THREAD

**Issue by mwoodpatrick** [mviereck/x11docker#234]
I have been using mobaxterm with wsl 2 and it has worked well for me. Any specific reason for not supporting it, any idea how much work that would be. I might try playing with integrating it if I can find the time.

**Comment by mviereck** [comment]
If I remember correctly, mobaxterm is closed source.
Because there are open source alternatives (XWin and VcXsrv), I see no need to include mobaxterm support. 
If at all it should be inluded in `runx` instead of x11docker: https://github.com/mviereck/runx
The effort would probably be not too hard, likely it can be included very similar to VcXsrv.
x11docker uses `runx` to provide X on MS Windows.

**Comment by mviereck** [comment]
Just reading again, maybe my answer sound a bit rude. Sorry, that's not intended.
Do you see an advantage of mobaxterm compared to the open source X servers?

**Comment by mwoodpatrick** [comment]
While its not open source I think it is an interesting & useful alternative to the  open source X servers. mobaxterm does allow for free use, it supports a variety of protocols (see https://mobaxterm.mobatek.net/) it is easy to install and has worked well for me, mobaxterm  has no other dependencies and  supports the GPU. I'm running on windows with WSL-2 & an NVidia card.  Apparently  VcXsrv has some issues with NVidia cards and XWin depends on cygwin which I would rather not install since I already have a real Linux kernel.

**Comment by mviereck** [comment]
I've looked a bit at the mobaxterm website. 
Just a thought: mobaxterm provides an X server and a bash terminal. Maybe it already works if you run 'x11docker --hostdisplay x11docker/check`. (Given that you can run docker in the mobaxterm terminal).

> I'm running on windows with WSL-2 & an NVidia card.

Could you please have a look at https://github.com/mviereck/x11docker/issues/214#issuecomment-602190534 and try x11docker on WSL2? It is supposed to work, but I cannot test myself.

**Comment by eine** [comment]
> While its not open source I think it is an interesting & useful alternative to the open source X servers.
>
> XWin depends on cygwin which I would rather not install since I already have a real Linux kernel.

I have the feeling that mobaxterm is nothing but a closed source package/GUI that integrates non-viral open source tools: cygwin, cygwin/X, Putty, etc. Hence, I would say that mobaxterm has the same advantages and disadvantages as cygwin/X. Of cource, this is difficult to prove because mobaxterm is closed source.

**Comment by mwoodpatrick** [comment]
Will investigate further and report back, many thanks for looking into this.

**Comment by mwoodpatrick** [comment]
It definitely does include cygwin looks like my version of mobaxterm uses version 3.0.4. However as I noted the software is free to use for home use and the professional version is only a $49 one time charge. The environment is nicely done so I would say its reasonable value for money, There are some credits to the underlying packages on the mobaxterm site though they could probably more clearly spelled out.

**Comment by eine** [comment]
My main point is that mobaxterm might be considered "a regular cygwin/X installation in some non-default location". If that works, x11docker might support mobaxterm implicitly. I.e., it would not be an officially supported package (because it is closed source), but it could be used with some options/settings.

I do see the value of having an integrated solution, specially for Windows users who are more used to all-included GUI tools. However, I am unsure about that target fitting the intended audience of x11docker users. I would expect the intended audience of x11docker to be familiar with CLI tools and with specific resources such as envvars, xvfb, SSH, permissions, etc. I believe the purpose of x11docker is to provide automation and ease the configuration, but not to hide the complexity of what's happening.

I've been the one who nudged @mviereck to support Windows hosts; and I do help testing MSYS2, WSL and cygwin. Nonetheless, this is still my very personal point of view, not any *ab auctoritate*.

**Comment by mviereck** [comment]
Although it is likely possible to support mobaxterm, I've decided not to work on it.
As I don't use MS Windows on my own, maintaining MS Windows setups is a lot of additional work. I rather want to focus on other projects.
