### ISSUE TITLE
Failed to run window manager image: x11docker/openbox sh -c 'openbox --sm-disable --config-file /etc/x11docker/openbox-nomenu.rc'

### ISSUE THREAD

**Issue by hakonhagland** [mviereck/x11docker#256]
I am testing `x11docker` on Ubuntu 20.04 and `docker` installed with `snap`:

```
INSTALL_DIR="$PWD"
git clone git@github.com:mviereck/x11docker.git
cd $HOME/bin
ln -s $INSTALL_DIR/x11docker/x11docker
docker pull x11docker/openbox 
```

Then I created a simple test `Dockerfile`:

```
FROM ubuntu:20.04
RUN apt-get update && apt-get install -y x11-apps
ARG user=hakond
ARG home=/home/$user
RUN useradd --create-home -s /bin/bash $user \
        && echo $user:ubuntu | chpasswd \
        && adduser $user sudo
WORKDIR $home
USER $user
ENV HOME $home
CMD xclock
```

and built the docker image:

    docker build -t xclock-ubuntu-2004 . 

and run it with `x11docker`:

    x11docker --xephyr xclock-ubuntu-2004 

The output is:

```
x11docker WARNING: User hakon is member of group docker.
  That allows unprivileged processes on host to gain root privileges.

x11docker note: Enabled X over TCP instead of sharing unix socket.

x11docker note: Docker was installed with snap. That causes some restrictions.
  Option --newprivileges=yes is enabled.
  Option --hostdisplay is not available because X can only be accessed over TCP. 
  Option --gpu only works with --xorg and --hostnet.
  It is recommended to install Docker natively instead of running it in snap.

x11docker note: Xephyr is a quite stable nested X server.
  Less stable, but resizeable is nxagent with option --nxagent.

x11docker WARNING: Option --newprivileges=yes: x11docker does not set 
  docker run option --security-opt=no-new-privileges. 
  That degrades container security.
  However, this is still within a default docker setup.

x11docker note: Found 'USER hakond' in image. 
  If you want to run with user hakond instead of host user hakon, 
  than run with --user=RETAIN.

x11docker note: Found 'WORKDIR /home/hakond' in image.  
  You can change it with option --workdir=DIR.

x11docker note: Option --wm: Starting window manager image: x11docker/openbox sh -c 'openbox --sm-disable --config-file /etc/x11docker/openbox-nomenu.rc'

x11docker note: Option --wm: Failed to run window manager image: x11docker/openbox sh -c 'openbox --sm-disable --config-file /etc/x11docker/openbox-nomenu.rc'.

x11docker note: Option --wm: Starting host window manager: mutter
```

The `xclock` window shows fine in the Xephyr X server window. That is great! But I have some questions to the output in the terminal:

- What does it mean that it failed to run openbox:
```
x11docker note: Option --wm: Failed to run window manager image: x11docker/openbox sh -c 'openbox --sm-disable --config-file /etc/x11docker/openbox-nomenu.rc'.
```

- Also I cannot get `--hostdisplay` to work, and it seems from the output that it is related to `docker` being run from `snap`?

**Comment by mviereck** [comment]
> What does it mean that it failed to run openbox:

x11docker wants to provide a window manager in Xephyr unless option `--desktop` is specified. If available, it uses `x11docker/openbox` instead of a host window manager.

It seems that running the image `/x11docker/openbox` failed. Likely that is related to `snap`, I'll have to look closer at the generated Docker command.
Could you please provide me the logfile at www.pastebin.com after running this? (`~/.cache/x11docker/x11docker.log`)

> Also I cannot get --hostdisplay to work, and it seems from the output that it is related to docker being run from snap?

`snap` causes several restictions. `--hostdisplay` does not work because it is not possible to share unix sockets from host, in this case the X unix socket in `/tmp/.X11-unix`.

I recommend not to use `docker` in `snap` but to install docker with `apt` instead.
Both are container solutions, and running a container in another container does not make sense.

> USER $user

Note that x11docker overwrites user settings in image. Instead it generates a container user similar to the host user and overwrites `/etc/passwd`, `/etc/group` and `/etc/shadow`. Compare https://github.com/mviereck/x11docker#security
You can use `--user=RETAIN` to keep image user configuration.
