### ISSUE TITLE
x11docker on multi gpus server

### ISSUE THREAD

**Issue by pampanelson** [mviereck/x11docker#263]
I have multi nvidia gpus on a headless server which installed nvidia driver and nvidia container toolkit, I can run a docker with --privileged to let the container connect to host x server and set Xorg :1 & DISPLAY=:1 before opengl application start command for running with hardware accelerate inside docker.

but when I start two opengl application in seperate docker container both application crash.I guess there is conflict of using host x server.

my question is , is possible x11docker to handle this? let multi containers run at same time and with own specific gpu hardware acceleration.  

thanks

**Comment by mviereck** [comment]
> but when I start two opengl application in seperate docker container both application crash.I guess there is conflict of using host x server

I am not sure where the underlying issue is. It is the regular case that multiple applications use the same X server. So I don't know if x11docker will make a difference here.

With proprietary NVIDIA driver x11docker options are limited and the containers would have to share the host X server, too.

However, you might have a look at docker run option `--gpus` that allows to specify with NVIDIA GPU resources to use. x11docker does not use it because support for other vendors like AMD is not implemented, not even in a basical matter.

My recommendations:
 - Just try out if using x11docker makes a difference. Regard the wiki: https://github.com/mviereck/x11docker/wiki/NVIDIA-driver-support-for-docker-container
 - Try out docker run option `--gpus` and read its documentation. Although x11docker does not include it directly, you can add it as a `DOCKER_RUN_OPTION` in x11docker syntax:
```
  x11docker [OPTIONS] -- DOCKER_RUN_OPTIONS -- IMAGE [COMMAND [ARG1 ARG2 ...]]
```
