### ISSUE TITLE
Best tool for manage docker

### ISSUE THREAD

**Issue by ps-a** [mviereck/x11docker#289]
There're lot of GUI docker manage tools and x11docker also offer kaptain (according to screenshots, it seems doesn't cover all requirements)

- Download newer images by one click
- Stop, restart, start and remove using single buttons
- Keep the docker run cmd as a eg: profile even after removed container to deploy new container using new image (update)

What's the best tool available for cover that requirement? i dont want to play with terminal for x11docker start containers and image updates, it's headache task. any other tool better than that? https://dockstation.io/ or is that the best?

**Comment by eine** [comment]
Note that dockstation seems to neither be open source nor actively developed.

The official solution is Docker Dashboard. But I think that's only available on Windows and mac OS.

VSCode has a nice support through the Docker extension and the remotes extension. x11docker can be integrated quite nicely: https://github.com/microsoft/vscode-docker/issues?q=is%3Aissue+x11docker+is%3Aclosed. With VSCode you can use either Docker or WSL2.

For something as similar as possible to dockstation, you might want to try Portainer.

**Comment by mviereck** [comment]
> There're lot of GUI docker manage tools and x11docker also offer kaptain (according to screenshots, it seems doesn't cover all requirements)

`x11docker-gui` covers all x11docker options and also allows to add custom docker options. It has some tabs that offer more options but are not visible in the screenshot.

> Download newer images by one click

x11docker has an option `--pull=always` that always pulls a newer image if available.

> Stop, restart, start and remove using single buttons

In general GUI applications are stopped by closing their windows. `docker stop ID` is possible, too.
x11docker does not offer to stop and restart a container, it always removes stopped containers and creates new ones from the image.

> Keep the docker run cmd as a eg: profile even after removed container to deploy new container using new image (update)

I've considered to extend `x11docker-gui` to store several "profiles". I've decided against because most users prefer the cli and only use x11docker-gui until they are familiar with the options.
`x11docker-gui` is used in practice rather to set up a command once and than copy it to clipboard. The command can be stored than in a one-liner script.
Alternatively, `x11docker-gui` can create a starter on the desktop.

> What's the best tool available for cover that requirement? 

@eine Thanks for your suggestions!
I personally do not know other GUI tools than `x11docker-gui` that could be used as a frontend.

**Comment by eine** [comment]
@mviereck, my opinion is that features provided by Docker Dashboard, VSCode, Portainer, dockstation, etc. are out of the scope of x11docker. The purpose of x11docker is not managing one or multiple docker hosts. Instead it is for starting X servers and/or attaching containers to X servers.

VSCode is compatible with x11docker. Docker Dashboard should also work, but I did not try it yet.

**Comment by ps-a** [comment]
@eine i forgot to tell that, i'm linux(ubuntu) user and vscode more friendly for dev environment but my requirement bit different as for daily user. thanks for explanation ^_^

>@mviereck  x11docker has an option --pull=always that always pulls a newer image if available.

I often use dev builds. in this cause, it's unnecessary to download every builds. usually check changelog before download image and i dont like something make network request frequently or every day.

>In general GUI applications are stopped by closing their windows. docker stop ID is possible, too.
By design x11docker does not offer to stop and restart a container,

i also expect to cover non-x11docker instances using one software.

>I've considered to extend x11docker-gui to store several "profiles". I've decided against because most users prefer the cli and only use x11docker-gui until they are familiar with the options.

Not really. i have several x11docker instances 5-8 ofcourse it's headache to play with cli when necessary

Conclusion: i think there are no better alternative to dockstation. unfortunately even it isn't opensource and i'll check `x11docker-gui` Thank you too for develop this nice x11docker :superhero: :1st_place_medal:
