### ISSUE TITLE
Xephyr help !! isolating keyboard

### ISSUE THREAD

**Issue by velcrine** [mviereck/x11docker#351]
Hello mviereck sir, U are legend of Xserver. I need one help.

in x11Docker script, what argument can I attach to Xephyr so that I can start migrating the script to allow exclusive/isolated/non-sharing input devices access to each Xephyr x session. 
Earlier we were able to use evdev, but as now the support is gone, what can I do sir.
Help is very much  appreciated

**Comment by mviereck** [comment]
I am not sure if I understand your question.
Input devices are mouse or keyboard. The currently active Xephyr window gets mouse and keyboard events, inactive Xephyr windows don't. So what do you want do isolate more than that?

**Comment by velcrine** [comment]
Thanks mviereck for quick response.
By isolation, I meant a multiseat kind of setup. Where keyboard and mouse for one person are attached to just one window / monitor. His keyboard can not enter my workera, and can't give any input. However, I was able to provide that using older version of Xephyr that had evdev support. But I am stuck with audio now. How can I make sure, audio from one docker image, reaches to a particular audio device( head phones). So that audio from multiple docker containers dont mix up, and reach to seperate audio devices.
Thanks

**Comment by mviereck** [comment]
> How can I make sure, audio from one docker image, reaches to a particular audio device( head phones). So that audio from multiple docker containers dont mix up, and reach to seperate audio devices.

I am not sure about this. I am not familiar with this kind of setup.
Basically I see two ways:
 - x11docker option `--alsa` shares entire `/dev/snd`. If you have multiple audio devices (one for each user) you could share only the desired one to a container instead of using `--alsa`. Something like `x11docker --xephyr -- --device /dev/snd/hwC1D0 -- image` for one user and a different device for another user. However, I don't know which device files are exactly needed inside of `/dev/snd`.
 - x11docker option `--pulseaudio` connects the container to pulseaudio server on host. pulseaudio should be configurable to distribute sound input and output according to containers and users. However, setting this up might be a mess, and maybe users could be able to change the config within their container to listen to the aothers.

**Comment by velcrine** [comment]
Thanks mviereck. That has given me info enough. 
I am very grateful for x11docker project and its dedication for community. I am a developer in golang. Tell me in case  I can be of any help in any project of yours, that doesn't use shell.
