### ISSUE TITLE
Can containerd replace docker 

### ISSUE THREAD

**Issue by liyimeng** [mviereck/x11docker#357]
As I understand, docker is required to run x11docker image, is it possible to option it to containerd, which should provide the similar runtime.
  
I love to see this happen is that it will allow x11docker run on kubernetes node, which has decided to  optioned out docker already.

**Comment by mviereck** [comment]
I found that the containerd project provides a cli [nerdctl](https://github.com/containerd/nerdctl) that should be able to replace the command `docker` in place with same syntax.

I've added an experimental option `--backend=BACKEND` that allows you to set `--backend=nerdctl`. This will cause x11docker to use command `nerdctl` instead of `docker`.

Please try out if that works for you. If issues come up, please report, maybe they can be fixed.

**Comment by mviereck** [comment]
I've added support for `--backend=nerdctl`.

Note that `nerdctl` only supports a subset of `docker` options. Some x11docker options are not available yet due to this restriction. 
Especially `nerdctl inspect IMAGENAME` does not work and disallows some container setup for x11docker. Another restriction is missing option `--group-add` that disallows options `--webcam`, `--gpu` and `--alsa`.

**Comment by mviereck** [comment]
Thank you!
Did not thought it could be that easy.

**Comment by mviereck** [comment]
I've included support for `nerdctl` as good as is possible now.

Currently `nerdctl` does not support `nerdctl inspect IMAGENAME` (https://github.com/containerd/nerdctl/issues/222). x11docker needs this to obtain `CMD` and `ENTRYPOINT` from image.
This in turn requires you user to provide a container command to execute if you want to use all x11docker features. Otherwise a restricted fallback mode (option `--no-setup`) will be used.

**Comment by liyimeng** [comment]
@mviereck superb! I will give a test!

**Comment by mviereck** [comment]
> Currently nerdctl does not support nerdctl inspect IMAGENAME (containerd/nerdctl#222). x11docker needs this to obtain CMD and ENTRYPOINT from image.
This in turn requires you to provide a container command to execute if you want to use all x11docker features. Otherwise a restricted fallback mode (option --no-setup) will be used.

nerdctl now supports `nerdctl inspect $image` since release [v0.9.0](https://github.com/containerd/nerdctl/releases/tag/v0.9.0), so it is no longer required to provide a container command.
