### ISSUE TITLE
x11docker ERROR: Option --share needs an argument

### ISSUE THREAD

**Issue by jJit0** [mviereck/x11docker#358]
Hi,

When I launch x11docker-gui I get this error:
`x11docker ERROR: Option --share needs an argument`

`x11docker-gui: Startup of x11docker/kaptain was not successfull.
  Please install package kaptain or provide image x11docker/kaptain
  with:   docker pull x11docker/kaptain`
  
I don't get it, because I already have Kaptain Image: docker pull x11docker/kaptain
`x11docker/kaptain        latest    6f09e3ecdfc2   9 months ago   141MB`

Any ideas why I get this error when I try to launch x11docker-gui only ?

**Comment by mviereck** [comment]
Thank you for the report.

There has been a bug in `x11docker-gui`. Not sure how old it is, did not check it too long.
Please update to master version to get the fix with `x11docker --update-master`.

**Comment by jJit0** [comment]
Ok, I did this command `x11docker --update-master`

But still the same error after launching x11docker-gui

**Comment by mviereck** [comment]
> But still the same error after launching x11docker-gui

oh, ok. Likely you have to wait some minutes until github generates a new zip file from the source code.
Please try again a bit later.

**Comment by jJit0** [comment]
Ok no problem ;)

**Comment by jJit0** [comment]
All good for me after git pull in the x11docker dir

Thanks a lot ;)

**Comment by mviereck** [comment]
Great!

**Comment by jJit0** [comment]
Have you tried to port x11docker to python as a pypi packer, golang-go or even as a deb package ported to debian repos ?

**Comment by mviereck** [comment]
> Have you tried to port x11docker to python as a pypi package, golang-go or even as a deb package ported to debian repos ?

There is a discussion about porting x11docker, maybe to golang.
Currently I am only skilled in bash scripting. I consider to learn C++ or python3 because I need advanced GUI capabilities for another project ([microscopy-tools](https://github.com/mviereck/microscopy-tools)).

A debian package would be already possible with the current bash script. If the Debian maintainers would consider to include x11docker, I would be honored. Though, I didn't ask for it.
For [arch](https://aur.archlinux.org/packages/x11docker/), [alpine](https://pkgs.alpinelinux.org/package/edge/testing/x86/x11docker) and [NixOS](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&query=x11docker) there are already packages set up by volunteers.

**Comment by umarcor** [comment]
FTR, eventually there might be a package on MSYS2 too: https://github.com/msys2/MINGW-packages/pull/8044.

**Comment by jJit0** [comment]
Very nice,

Wish I can help, Unfortunately I just know bash also.

**Comment by mviereck** [comment]
@umarcor  Thank you for your PR at MingW!

@eine You might be interested to have a look there, too. https://github.com/msys2/MINGW-packages/pull/8044
