### ISSUE TITLE
Both x11docker and x11docker-gui should be installed to /usr/local/bin to prevent package manager confusion

### ISSUE THREAD

**Issue by N0rbert** [mviereck/x11docker#371]
I have a suggestion which is presented in the title.
It is strange that x11docker installs itself into package-manager-controlled directory - `/usr/bin`.
Please change the installation folder to `/usr/local/bin` to ease system administration and to make it more transparent.

**Comment by mviereck** [comment]
I agree that `/usr/local/bin` fits better for applications that are not installed by a package manager.

The reason why I decided to use `/usr/bin` instead:
`/usr/local/bin` is  mostly not in `PATH` of user `root` and can also miss if using `sudo`.
But x11docker needs root privileges to run docker if the user is not in group `docker`.
Adding `/user/local/bin` to `PATH` of root is also not recommended.

So x11docker needs to be installed in `/usr/bin`.
Alternatively, to avoid `/usr/bin` and `/usr/local/bin` as well, it could be installed in `/opt/x11docker/bin`. The user would have to add this path to `PATH` manually.

A possible solution: x11docker would still install in `/usr/bin` by default, but optionally allow alternate installation pathes. Option `--update` should automatically detect and regard the installation location.

**Comment by N0rbert** [comment]
> A possible solution: x11docker would still install in /usr/bin by default, but optionally allow alternate installation pathes. 
> Option --update should automatically detect and regard the installation location.

Personally I will be very happy with this proposed solution.
On first installation of 6.6.2 I have manually moved x11docker executables to `/usr/local/bin`, but latest `--update` to 6.9.0 removed them and installed to `/usr/bin` instead. So I have manually moved them to `/usr/local/bin` again. This last step should be automated :)

**Comment by mviereck** [comment]
I've included this in the current beta/master version.
There is still no argument for `--install`, but `--update` and `--update-master` will regard a custom installation path.
I still have to do some adjustments (especially in case of a location in `HOME`), but for your case it will already work.

However, If you run `--update-master` now, you'll have to move the files again one time because an older version of x11docker does the update. Same issue will occur if you run `--update` before a new stable release is published. The current stable release would install to `/usr/bin` again on next update.

**Comment by mviereck** [comment]
Since v7.6.0 x11docker installs itself into `/usr/local` by default: 
https://github.com/mviereck/x11docker/releases/tag/v7.6.0
https://github.com/mviereck/x11docker/issues/479
