### ISSUE TITLE
Could you officially open a window to run host-terminal command in docker?

### ISSUE THREAD

**Issue by djypku** [mviereck/x11docker#396]
This is an advice.
------------------------------------------------------------------------------------------------------------------------
It is said that we can use
`nsenter -t 1 -m -u -n -i sh -c "<host command>"`
to run host command in docker, but with an extremely high privilege. I have not managed to do so now, for my x11docker is one got from `dnf` by Fedora and it is rather out-of-time and so that there is no things like `--privileged` or so on. I will try newer version after my exam to find out whether it is possible (I guess so).
Some much easier and more secure way is to leave a daemon in host to keep reading some files shared by host and docker and then run anything it reads from there, and you can just write commands to that file in docker. While it is safe, I think that too slow and easy to get error ( for two programs are reading/writing the same file), and it costs too much resource.
On the other hand, yes, I can run a xterm to control host, but it is very inconvenient and rigid. Be able to remain controls of host in docker is something really amazing. Would you like to leave a window such as
`hostrun <command>`
to run host command in docker? What I mean is that to give a special privilege ONLY to this command to enhance communication while not destroying security too much. I think it a good idea.
Thanks.

**Comment by mviereck** [comment]
x11docker has an option `--runfromhost CMD` that partially does what you want.
For example, 
```
x11docker --runfromhost xterm --desktop x11docker/xfce
```
will run xterm from host on the same X server as the containered Xfce desktop does.
However, the container cannot control the host xterm except using the X11 protocol.
It would be possible to type in commands with tools like `xdotool`. But that is hacky and not elegant.

--------------

Your attempt of a shared file is basically the right unix way. But instead of a regular file I recommend to use (and share) a fifo pipe (compare `man mkfifo`). 
This is too specific for an x11docker option, but possible to set up with the help of `--share` or `--volume`.

---------------

> I have not managed to do so now, for my x11docker is one got from dnf by Fedora and it is rather out-of-time and so that there is no things like --privileged or so on

The fedora version is rather actual. If you look at the changelog you'll that that the changes from 6.9.0 to 6.10.0 are minor.
You already can add `--privileged` as a custom run option. Compare:
```
  x11docker [OPTIONS] -- RUN_OPTIONS -- IMAGE [COMMAND [ARG1 ARG2 ...]]
```
However, I always discourage the use of `--privileged`.
