### ISSUE TITLE
Anyway to save changes? [docker export]

### ISSUE THREAD

**Issue by djypku** [mviereck/x11docker#407]
I need to save changes in `/etc`. I try `--share=/etc` and trigger great problems almost break down my computer.
If using `docker`, it is possible to use `docker export`. However, here seems nothing similar for  `x11docker`.
Then I have little idea about it.

**Comment by djypku** [comment]
For `/etc`, I think maybe possible to use ` -v xxx:/etc ` to do that work. However, on the other hand, no idea about how to export an image out from `x11docker`.

**Comment by mviereck** [comment]
The recommended way is to change the underlying image.
For example, create a config file that should appear in `/etc` and add it to the Dockerfile with build instruction `COPY`.
For example, to configure `cups`, have a folder containing the Dockerfile and your config file.
Add a line `COPY cupsd.conf /etc/cups/cupsd.conf` to the Dockerfile and build again.

**Comment by mviereck** [comment]
>  If using docker, it is possible to use docker export. However, here seems nothing similar for x11docker.

It is possible to use `docker export` while x11docker is running. Check the output of `docker ps` or use x11docker option `--showid` to get the container id.

However, I highly discourage this because it leads to not reproducible and thus unmaintainable images.
Rather adjust the image build as suggested above.
