### ISSUE TITLE
x11docker with Debian bullseye weston [SSH]

### ISSUE THREAD

**Issue by mfloiot** [mviereck/x11docker#413]
Hi, 
first all thanks for the very good documentation, especially regarding the various dependency options: https://github.com/mviereck/x11docker/wiki/Dependencies#recommended-base 

I'm new to the project and I would like to setup a configuration where you install minimal software packages on the host system and use a container to execute a chrome browser in kiosk mode.

In order to check feasibility of the approach, I thought just installing weston in a debian bullseye system and follow the steps in:
https://github.com/mviereck/dockerfile-x11docker-xwayland

Unfortunately I always get an error:
"fatal: failed to create compositor backend"
when executing he container by:
x11docker --wayland --weston --gpu x11docker/xwayland
or
x11docker --weston --gpu x11docker/xwayland

Any idea what goes wrong?

Here is the log:
[x11docker.log](https://github.com/mviereck/x11docker/files/8032643/x11docker.log)

**Comment by mviereck** [comment]
Thank you!

I did not found an exact reason for the startup failure, except maybe one: Did you start over SSH instead of directly? The log indicates that.

Did you run `weston` first, than inside of weston `x11docker`? 
Or did you run x11docker directly from console? (That might not be possible over SSH.)

**Comment by mfloiot** [comment]
Hi, you were totoally right. I thought I could start it via an SSH session. If I start the container directly, it worked well.
Thanks for the hint!

**Comment by mviereck** [comment]
You could still start over SSH with `ssh -X` using the X server of your client machine.

**Comment by mfloiot** [comment]
Sorry .. another question. 
Is there somewhere a template for a systemd service file which starts the x11docker container at startup?
Maybe something like "podman generate systemd ..." would be cool.

FYI, I'm using a podman backend in rootless mode.

**Comment by mviereck** [comment]
> Sorry .. another question.

No problem. :-) Just please open new questions in new tickets.


> Is there somewhere a template for a systemd service file which starts the x11docker container at startup?
Maybe something like "podman generate systemd ..." would be cool.

So far there is no template, and I did not set up something like this. What would be the use case?

**Comment by mfloiot** [comment]
> > Sorry .. another question.
> 
> No problem. :-) Just please open new questions in new tickets.
> 
I'm still in evaluation whether the x11docker does fit in general to my needs. 
If yes, I will raise a new request.

> > Is there somewhere a template for a systemd service file which starts the x11docker container at startup?
> > Maybe something like "podman generate systemd ..." would be cool.
> 
> So far there is no template, and I did not set up something like this. What would be the use case?
The usecase is that I would like to start a container running a browser in kiosk mode at startup.

**Comment by mviereck** [comment]
>  The usecase is that I would like to start a container running a browser in kiosk mode at startup.

A different attempt that could achieve the same: https://github.com/mviereck/x11docker/wiki/Display-manager-entry-for-x11docker
You could configure a display manager like lightdm to autologin to an x11docker session.

**Comment by mviereck** [comment]
I've set up a systemd service to run x11docker with firefox as a systemd service: (replace `mviereck` with the desired user name)
```
$ cat /etc/systemd/system/x11docker-jess-firefox.service 
[Unit]
Description=x11docker jess/firefox
After=systemd-user-sessions.service docker.service

[Service]
ExecStart=/bin/su - -- mviereck -l -c 'x11docker --network -- --tmpfs /dev/shm -- jess/firefox'
StandardOutput=syslog

[Install]
WantedBy=multi-user.target
```

If there is a display manager like `lightdm` on the system, it should be disabled with `systemctl disable lightdm`. Otherwise the x11docker session and the display manager start in parallel.

After the container terminates, the user sits at the login prompt of a console.
To avoid this, it is possible to add a `poweroff` command to the service.
To allow a passwordless `poweroff`, add this line to `/etc/sudoers`:
```
mviereck ALL=NOPASSWD:/sbin/poweroff
```
This service will shut down the computer once the container terminates:
```
$ cat /etc/systemd/system/x11docker-jess-firefox.service 
[Unit]
Description=x11docker jess/firefox
After=systemd-user-sessions.service docker.service

[Service]
ExecStart=/bin/su - -- mviereck -l -c 'x11docker --network -- --tmpfs /dev/shm -- jess/firefox ; [ "$?" != 64 ] && sudo poweroff'
StandardOutput=syslog

[Install]
WantedBy=multi-user.target
```
While the container runs, it is possible to switch to other consoles with STRG+ALT+Fn.
In case x11docker itself has a startup error, the computer will not shut down but sit at login prompt thanks to the check for error code 64. This allows to access the console for debugging.

Pitfalls:
 - `su` triggers a valid systemd logind login on debian. This is not the case on arch or alpine.
 - Currently only Xorg works. A startup with weston fails. I'll investigate. It might need a combination with a `getty` service.
 - In case of `docker` the user must be in group `docker`. Alternatively `--backend=podman` can be used.
 - In case x11docker succeeds, but the container application immediately crashes, it is not possible to access a console due to `poweroff`.
