### ISSUE TITLE
x11docker --share not working on WSL2

### ISSUE THREAD

**Issue by raisen** [mviereck/x11docker#424]
I've been using x11docker from an Ubuntu host and has been working fine. Recently I tried to run it from a WSL2 setup and noticed the --share parameter is not working properly. x11docker claims the folder doesn't exist when I run something like: x11docker --share=/mnt/c . It doesn't give me an error when I do either:
 a. --share=\mnt\c
 b. --share=//mnt//c
 but the folder isn't visible on the container.

The error I receive is:
x11docker ERROR: Option --share: File or folder does not exist:
  /c

It seems that x11docker is parsing the parameter as a regular expression?

Any suggestions on how to troubleshoot this further?

Versions tried: 7.1.4-beta-3 and 7.1.3

**Comment by mviereck** [comment]
Thank you for the report!
Unfortunately i don't have a Windows test environment yet.

Could you please try `--share=/mnt/c/` instead of `--share=/mnt/c`? Appending `/` might make a difference if you try to share entire drive `c`. (x11docker might parse wrong in that case.)

Always use `/` instead of `\` to avoid escape errors.

**Comment by raisen** [comment]
Thank you @mviereck , that indeed fixed the problem. I actually moved back to a *nx environment, but I switched back to WSL2 to try your change and that fixed the problem.
Thank you for your commitment to this project.

**Comment by raisen** [comment]
FYI, I tried with:
````
x11docker --version
7.1.4-beta-7
````
