### ISSUE TITLE
x11docker/check - unmet dependencies:  kaptain ...

### ISSUE THREAD

**Issue by jonathancross** [mviereck/x11docker#436]
Hi, noob here.
I am trying to run `x11docker` as an unprivileged user and can't even get `x11docker/check` to run:

```
docker pull x11docker/xserver
Using default tag: latest
latest: Pulling from x11docker/xserver
Digest: sha256:1912e7fbeaac53fa2cf4c73d32c9397792de94f38503ccfed83f124869368c72
Status: Image is up to date for x11docker/xserver:latest
docker.io/x11docker/xserver:latest



x11docker --verbose --build x11docker/check

...

The following packages have unmet dependencies:
 kaptain : Depends: libqt4-qt3support (>= 4:4.5.3) but it is not installable
           Depends: libqtcore4 (>= 4:4.5.3) but it is not installable
           Depends: libqtgui4 (>= 4:4.5.3) but it is not installable
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c curl http://ftp.us.debian.org/debian/pool/main/k/kaptain/kaptain_0.73-2_amd64.deb -o /opt/kaptain.deb &&     cd /opt &&     env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends ./kaptain.deb' returned a non-zero code: 100

x11docker ERROR: Option --build: Building image 'x11docker/check' failed.
```

I tried to figure out what `kaptain` was and why it was failing, but am just confused by messages like this:
https://github.com/mviereck/x11docker/blob/2c61c100bd17026ce75b9d08dd876e28acbc3309/CHANGELOG.md?plain=1#L131

**Comment by mviereck** [comment]
Thank you for the report!

Just to clarify: If you have pulled image `x11docker/check`, you don't need to also build it with `x11docker --build`.
You can just run it with `x11docker x11docker/check`.

About the issue with `x11docker --build x11docker/check`: Accidentely I forgot to update the Dockerfile. It fails to build with image debian bullseye but needs the previous release debian buster. I've uploaded a fixed Dockerfile yet. `kaptain` fails to install on debian bullseye.

However, building with `x11docker --build x11docker/check` still fails because the image uses several additional files added with a`COPY` instruction that are not regarded yet by x11docker. I'll have to fix that.

`x11docker-gui` was a GUI frontend for x11docker that I have deprecated. It is not related to image `x11docker/check`.
