### ISSUE TITLE
Confusion over --network

### ISSUE THREAD

**Issue by jcalfee** [mviereck/x11docker#441]
With `--network=host` my published ports do not map anymore and instead default to the port the container is using:
> WARNING: Published ports are discarded when using host network mode

What is the equivalent before the `network` parameter became required?  Was it bridge?  I fumbled around and eventually fixed it using bridge.  Given that networking is important for many containers, I hope you may consider some tweaks to the documentation.  

This was misleading me into using the `--network` parameter without a second value:
>    - For internet access use option `-I, --network`.

And here:
> To allow internet access set option -I or --network.

And the reference to the go look at docker help about this parameter is hiding in the change log.  I would just tell them straight-up by giving the example `--network=bridge` and should probably mention these are values on your network found by running `docker network ls`.

**Comment by mviereck** [comment]
Thank you for the report!
The current documentation `x11docker --help` says:
```
 -I, --network [=NET]  Allow internet access.
                       For optional argument NET see Docker documentation
                       of docker run option --network.
```
In fact, option `--network` without an argument just does no network setup at all. So the docker default takes place. This is normally `--network=bridge` as you already found out.
Maybe I should make this clear somehow in the documentation.
What about:
```
 -I, --network [=NET]  Allow internet access. (i.e. allow docker default.)
                       For optional argument NET see Docker documentation
                       of docker run option --network. Docker default is bridge.
```

>  I would just tell them straight-up by giving the example --network=bridge and should probably mention these are values on your network found by running docker network ls.

x11docker could set `--network=bridge` instead of setting nothing. Than I could document `bridge` as default.
I hesitated to do so because one might have configured his docker daemon in another way.
`docker network ls` does not tell the possibility to connect to other network namespaces, notable those of other containers.

**Comment by jcalfee** [comment]
Any blurb about "bridge" should help remind someone earlier so I think that will help a lot.  Also, having the `=` in there anywhere you use it is important especially because your network command differs a little from docker's.  At one point I was trying to use a space and a network name without the equal sign (like you would in Docker).

I retested and it is working as your describing above.

I see in the console you have a message too when x11 runs:
> If you need network and internet access, set option -I, --network.

Probably good to have the = and NET there too.
> If you need network and internet access, set option -I,  --network [=NET].

**Comment by mviereck** [comment]
I've made a commit with the improved `--help` content.

> Probably good to have the = and NET there too.
>  If you need network and internet access, set option -I, --network [=NET].


I've added your suggestion, too.
