### ISSUE TITLE
Absolute minimum requirement on host

### ISSUE THREAD

**Issue by liyimeng** [mviereck/x11docker#444]
I am a little confused. I see there is x11docker/xserver docker images. What dose it provide? If we have this image, what is the bare minimum requirement on host?  Base is needed of cause. X still needed?  GPU drivers still needed?  If I want a most clean host env, what is the absolute minimum requirements?

**Comment by mviereck** [comment]
>  If I want a most clean host env, what is the absolute minimum requirements?

It depends on what you want to do. To run a GUI in a docker container appearing on your monitor:
As a core you need bash, docker (or podman) and Xorg (+xinit).
Additionally recommended tools are xauth xclip xhost xrandr xdpyinfo.

> GPU drivers still needed?

Yes, Xorg needs them to access the monitor.

> I see there is x11docker/xserver docker images. What dose it provide?

x11docker/xserver provides nested X servers that can run in an already running X session, e.g. a desktop environment.
The supported x11docker X server options are documented here: https://github.com/mviereck/dockerfile-x11docker-xserver

**Comment by liyimeng** [comment]
Thanks a lot! @mviereck

**Comment by mviereck** [comment]
Since today x11docker supports to run Xorg in a container of `x11docker/xserver`. (You would need to update x11docker to latest beta, and also update the image `x11docker/xserver`.)
This reduces dependencies on host, x11docker should work with just `bash`+`docker`+`x11docker/xserver`
Running Xorg in container is still experimental; it might fail in different setups than mine and needs to be tested.
