### ISSUE TITLE
Consider sysbox CE support

### ISSUE THREAD

**Issue by Intensity** [mviereck/x11docker#467]
I came across https://github.com/nestybox/sysbox which looks interesting in that it's able to run `systemd` in the container just as it offers some security enhancements useful in their own right.

It may become a preferred runtime for some, perhaps as a result of the Docker acquisition. Yet, the CE version is available to all.

Some naive attempts on my end didn't result in success. This backend may be of interest to some, whether it's coming from the side of looking more like a VM or from the isolation side.

**Comment by mviereck** [comment]
> I believe if shiftfs is compiled into the kernel and is running, that older kernels, such as 5.10 could work and so >= 5.12 may not be a strict requirement.

Yes, at first x11docker supported sysbox with shiftfs and kernel 5.10.
But this setup is deprecated, in x11docker as well as in sysbox. I decided to support with kernel >=5.12 only.

> Is IPC/MIT-SHM support not easy to enable for sysbox?

It would work in few cases only where the X server container uses sysbox as well. sysbox cannot share device files yet, but some X servers would need it. Instead of checking several different cases, I decided to disable MIT-SHM for sysbox and wait for device sharing support instead.

> I came across errors with ssh -Y and so I wonder if this needs to be a limitation.

`ssh -Y` should just work. If you have issues, please open a new ticket and describe them.

**Comment by mviereck** [comment]
I found an `XAUTHORITY` issue for `ssh -Y`. It is fixed now.
Remaining issues:
 - x11docker over `ssh -Y` needs `--network` due to X over IP, but this is not checked yet. 
x11docker should print a message.
 - Furthermore, the X server container sets `--network=none`, so currently it works only with `--xc=no`.
