### ISSUE TITLE
x11docker --update wont exit

### ISSUE THREAD

**Issue by rreutebuch** [mviereck/x11docker#47]
If i run x11docker --update, it looks like the installation works but it never exits. 
the last lines are:
```
 - Newdisplaynumber for xorg starts with 8
 - xinitrc: XPRA_OPENGL_DOUBLE_BUFFERED=1 to avoid xpra bug 1469
 - check and set XDG_RUNTIME_DIR for weston and Xwayland
 ###  Removed
```
and after that i have a blinking cursor for almost an hour now.

I am running x11docker inside a chroot environment (Debian 9)
everything worked fine when i ran the command the last time (about one week ago)

**Comment by rreutebuch** [comment]
i used an older version of x11docker (downloaded about 5 weeks ago) and now the `x11docker --update` command is working properly

**Comment by mviereck** [comment]
Thank you for reporting!
Good to hear the bug is already gone.

Unfortunately, there is not much I can do with x11docker versions out there containing the bug. I can only hope that no one will be annoyed about it.

I did major changes in background process and exit handling in the last few weeks, sometimes the beta versions still had a bug. I don't know, maybe it was a beta/master version instead of a release you had before. 
(`x11docker --update` downloads latest release, `x11docker --update-master` downloads latest master/beta version).
