### ISSUE TITLE
Multi monitor whole desktop system?

### ISSUE THREAD

**Issue by groupmsl** [mviereck/x11docker#474]
Hello,

I have a desire to run an entire desktop and all applications in a container. This will allow me to have different versions of window manager, applications etc. It will also allow me to test and try things without worrying that I'll break my system and have to spend ages setting it up again.

I have a multi monitor setup (4 HD monitors), and use Sway WM as my window manager - so Wayland based. I'd like to use all 4 of these monitors, as I do natively.

Is this possible? Does anyone have any pointers for how I should start?

I'd appreciate any help, thank you.

**Comment by mviereck** [comment]
In general this should work.
It's a while ago since I've tested a multimonitor setup.
I am not experienced with sway, though. sway uses Xwayland, so all x11docker options should work.

The possibilities or usability might depend on the chosen X server option. With `--xorg` (not using your host sway) it should look like a native installation and just use all monitors.
`--xephyr` and `--nxagent --desktop` rather open a single window.
`--weston-xwayland` supports `--output-count` to open one desktop across multiple windows.

I'd say, just try out, and tell me what works for you and what you are missing once it runs.
