### ISSUE TITLE
nix: python3 as dependency

### ISSUE THREAD

**Issue by k1mbl3** [mviereck/x11docker#478]
Please add "python3 "to the dependencies of the nix package. It took me days to discover in the source code that the missing "python3" was the culprit.

**Comment by mviereck** [comment]
Thank you for the report, and sorry for your trouble.
I cannot change the nix package myself because I am not the maintainer of it. This could be reported as a bug to nixOS.
My fault is that I did not document well this (rather new) dependency.
I have added some notes in x11docker wiki to address this.
Furthermore, I have added support for `jq` json parser as a lightweight alternative to `python`.
