### ISSUE TITLE
Crashing with Wayland and `--user=RETAIN`

### ISSUE THREAD

**Issue by TheFloatingBrain** [mviereck/x11docker#480]
Hello, 

Awesome project! Way more flexible to use than my little manager! I have a bit of a problem though, I am trying to run an application, and I don't want to import any external information into it, so I specified `--user=RETAIN` but this causes the application to crash, it works fine without this option, it also crashes if I specify `--user=user` (where `user` is a user I created in the dockerfile)

Here is the [log](https://gist.github.com/TheFloatingBrain/e68ff97548fd2b7cbdd8570eb0732053)

Running this with podman, with wayland and `--cap-add=SYS_CHROOT`

I do have a work around for the moment, using `x11docker/xfce` as a base image, but I would really like to be able to just use the windows on my host desktop

Thanks!
 - TFB

**Comment by mviereck** [comment]
> Awesome project! 

Thank you! :-)

I see two issues:
 - firefox does not run on Wayland if just run with command `firefox`. IIRC it also needs x11docker option `--env MOZ_ENABLE_WAYLAND=1`. In the log firefox tries to detect an X server instead of using Wayland.
 - The Wayland socket on host is owned by the current host user. If the container user has a different uid, the container applications cannot access the Wayland socket. You could either set the same uid, e.g. with `--user $(id -u):($id -g)`, or change the access permissions of the Wayland socket, e.g. `chmod 666 $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY`.
