### ISSUE TITLE
can't set timezone in Kodi - bind-mount /usr/share/zoneinfo?

### ISSUE THREAD

**Issue by ehough** [mviereck/x11docker#50]
A user of `ehough/docker-kodi` [reported](https://github.com/ehough/docker-kodi/issues/5#issuecomment-394887864) that they couldn't change the timezone in Kodi. After a little digging, I found that Kodi relies on the presence of the `/usr/share/zoneinfo` directory to allow the user to select their country and timezone. Manually bind-mounting this directory (read-only) into the container resolves the issue.

Do you think this would be worthwhile adding as a default feature for `x11docker`, much like is [already with `/etc/localtime`](https://github.com/mviereck/x11docker/blob/90cc4cbad05df55e1a72e76edc5a9306f89095f8/x11docker#L3928)? I'd guess that a number of other GUI apps (especially desktop environments?) would rely on reading this directory, and I can't think of any obvious drawbacks.

Thoughts?

**Comment by ehough** [comment]
I suppose another option would be to install `tzdata` into the image at build time. This would negate the need for the bind-mount, but would increase the image size by a few MB. Not sure which approach is better.

**Comment by mviereck** [comment]
I did a test with `-v /usr/share/zoneinfo:/usr/share/zoneinfo:ro` and found that I get wrong times with other images, e.g. 
```
x11docker --nothing --stdout -- --volume=/usr/share/zoneinfo:/usr/share/zoneinfo:ro x11docker/lxde date
```
I get the right time with:
```
x11docker --nothing --stdout x11docker/lxde date
x11docker --nothing --stdout ubuntu:18.04 date
x11docker --nothing --stdout -- --volume=/usr/share/zoneinfo:/usr/share/zoneinfo:ro ubuntu:18.04 date
```
Now I am confused.
I tried to add some variants of `--env TZ=` as suggested at http://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html, but with no success.

As the issue is specific to kodi within ubuntu 18.04, and ubuntu:1804 has no issue with shared `/usr/share/zoneinfo`, I suggest to add `--volume=/usr/share/zoneinfo:/usr/share/zoneinfo:ro` to your kodi command instead of implementing it in x11docker.

Though, if we find a general solution that works for other images, too, I am willingly to include it in x11docker.

**Comment by ehough** [comment]
I ran your tests and got the same results. Super confusing.

After some more research, I think I discovered the cause. Turns out that Docker has a [slightly strange behavior](https://github.com/moby/moby/issues/14220#issuecomment-139710918) when you perform a single-file bind-mount into a container on top of an existing symbolic link (e.g. mounting `/etc/localtime` into the container). Instead of replacing the link, Docker will replace the link's *target* file. Weird. So when we bind-mount `/etc/localtime` by itself, we see the following:

```
$ docker run -it --rm -v /etc/localtime:/etc/localtime:ro debian
  # ls -l /etc/localtime
  lrwxrwxrwx 1 root root 27 Apr 25 17:00 /etc/localtime -> /usr/share/zoneinfo/Etc/UTC
  # ls -l /usr/share/zoneinfo/Etc/UTC
  lrwxrwxrwx 1 root root 6 Mar 26 15:43 /usr/share/zoneinfo/Etc/UTC -> ../UTC
  # ls -l /usr/share/zoneinfo/UTC    
  -rw-r--r-- 1 root root 2845 May  4 11:22 /usr/share/zoneinfo/UTC
  # mount | grep zone
  /dev/mapper/sdb4_crypt on /usr/share/zoneinfo/UTC type btrfs (ro,...,subvol=/usr/share/zoneinfo/America/Los_Angeles)
```
In other words, the container's copy of `/etc/localtime` eventually points to `/usr/share/zoneinfo/UTC`, which is actually my host's bind-mounted `/etc/localtime`. All good.

Now, what happens if we additionally mount `/usr/share/zoneinfo`? `/etc/localtime` again eventually points to `/usr/share/zoneinfo/UTC`, so that part doesn't change. But now `/usr/share/zoneinfo/UTC` already exists from within `/usr/share/zoneinfo` mount. The single-file bind-mount of `/etc/localtime` to `/usr/share/zoneinfo/UTC` is "overridden", and the container then assumes that it lives in UTC.

For Kodi, the reason the [behavior changed](https://github.com/ehough/docker-kodi/issues/5#issuecomment-394887864) between Ubuntu 16.04 (Xenial) and 18.04 (Bionic) is that `/usr/share/zoneinfo` exists in the former, but not the latter; Bionic doesn't have its own copy of `/usr/share/zoneinfo` to parse.

 In short, I don't think it would be wise to add `-v /usr/share/zoneinfo:/usr/share/zoneinfo:ro` to `x11docker`. Continuing to mount only `/etc/localtime` is the better solution.

**Comment by mviereck** [comment]
Thanks for your research! I admit I wasn't even aware that `/etc/localtime` is a symlink only. I once added it, was happy that it worked and forgot about it.

> In short, I don't think it would be wise to add -v /usr/share/zoneinfo:/usr/share/zoneinfo:ro to x11docker. Continuing to mount only /etc/localtime is the better solution.

An experiment that at least works with my examples above: I am sharing `usr/share/zoneinfo` and within the container I create the symlink:
```
ln -f -s $(readlink /etc/localtime) /etc/localtime
```
I've uploaded this change in master branch. Could you try out if it works with kodi, too?

**Comment by ehough** [comment]
That's a clever idea. I just tested [`233f3ef`](https://github.com/mviereck/x11docker/commit/233f3ef129ab53e67676b6d5c687fde1e1510da8) with Kodi and it works perfectly! Seems to me like this is a good solution.

**Comment by mviereck** [comment]
Currently I am in doubt if I should keep the solution sharing `/usr/share/zoneinfo` from host. 
It will cause trouble with images based on musl libc like alpine.

I am not sure how to solve this the best way.

Maybe I should only create the softlink `/etc/localtime` within container regardless if the target exists or not.

I just did a test with only providing the target file if libc from host and container match.
But kodi greyes out the timezone selection option if `/usr/share/timezone` only containes this single target.

I have to investigate further, just want to tell you that this may change again.

**Comment by mviereck** [comment]
I finally decided to change the timezone syncing procedure.

x11docker always sets environment variable `TZ`. 

If host and image both are based on glibc, x11docker provides only the one file where `/etc/localtime` points to. (Internally using a copy instead of a shared volume because x11docker does not know whether the container runs with musl libc before it is already running).

If the targeted timezone exists in container, the symlink `/etc/localtime` is created in container.

This works with debian and ubuntu bionic images as well as with alpine/musl libc.

Only kodi does not recognize the time zone settings and the provided timezone file, and the options to change it are greyed out :-(.  But kodi works if `tzdata` is installed.

I recommend to install `tzdata` in kodi image instead of sharing `/usr/share/timezone` from host because kodi would fail if the host is based on a libc different from glibc (e.g. alpine, Void, NixOS).

**Comment by ehough** [comment]
Thanks for this update! I tested it with Kodi (`tzdata` installed) and it seems to work just fine. I can't say I fully understand the details of the changes, but that's not my job, right? 😉

**Comment by mviereck** [comment]
> I can't say I fully understand the details of the changes, but that's not my job, right? wink

:-) It's confusing, and I did several tries and mistakes until it worked.

But, feel happy we don't have issues with keyboard mapping. Keyboard settings are a real PITA. :-D
