### ISSUE TITLE
GNOME + Wayland results in mutter error

### ISSUE THREAD

**Issue by sandrokeil** [mviereck/x11docker#56]
I'm testing the idea of #20 with a fresh arch linux installation. I'm using the Nouveau driver and can start a wayland gnome shell on host without Docker (`XDG_SESSION_TYPE=wayland exec dbus-run-session gnome-session`).

I've created an [Arch Linux Gnome Docker image](https://github.com/sandrokeil/docker-files/blob/arch/arch-linux/gnome) (`docker pull sandrokeil/arch-gnome:2018.06.01`) but it results in the following error if I start it from the host gnome shell (I don't know how to start a Wayland session via tty):

`x11docker --desktop --gpu --dbus --cap-default --hostipc --hostnet --sys-admin --hostwayland --verbose sandrokeil/arch-gnome:2018.06.01`

```
gnome-session-binary[78]: WARNING: Using null backend for session tracking

(gnome-shell:129): mutter-WARNING **: 11:00:48.819: Can't initialize KMS backend: Could not get session ID: No such file or directory
```

Maybe you have an idea to get mutter working? Here are the logs
[x11docker.log](https://github.com/mviereck/x11docker/files/2173549/x11docker.log)

**Comment by mviereck** [comment]
I already did several tries to run Gnome 3 in x11docker in different setups. Though, I did not try to run a Wayland session. Regardless what I try, Gnome 3 crashes. Often I found segfault messages in `dmesg` concerning `libmutter`. Same goes for Gnome 3 forks budgie and pantheon.
Only Cinnamon as an early fork of Gnome 3 runs well.

> Can't initialize KMS backend

The KMS backend needs direct access to the tty. If Gnome 3 would be more stable, a setup like in https://github.com/mviereck/x11docker/issues/40 could be tried.

Otherwise, `gnome-shell --help` provides options to change the backend. `--nested` would be worth a try to start it up like a weston window wthin X.

After a major update of Gnome 3 I will try again, maybe the segfault issues get fixed. But currently I don't see a way. `gnome-shell` even crashes in several setups if installed on host.

Sorry, no good news here. :-(
