### ISSUE TITLE
Is there a way to speed up container startup for pure console applications?

### ISSUE THREAD

**Issue by sandrokeil** [mviereck/x11docker#60]
I have a git container and I start it with `x11docker --stderr --stdout --silent --sharedir /home/skeil/data/sources --homedir=/home/skeil/data/x11docker/git --workdir $(pwd) --nothing -- --volume=$(dirname $SSH_AUTH_SOCK):$(dirname $SSH_AUTH_SOCK) --env=SSH_AUTH_SOCK=$SSH_AUTH_SOCK sandrokeil/archlinux:git` and compared to the native git command it's quite slow.

I don't know how much overhead has x11docker compared to the native Docker command but maybe you have an idea to speed up the container startup?

**Comment by 1138-4EB** [comment]
I think that a `--fast` or `--skip` option would be useful. If the container has been previously run, some configuration options can be read from a cache file. This can be useful in #55 too: if an X server is already running, there is no need to check it before starting each container.

**Comment by mviereck** [comment]
I did some trials to create a `fastrun.sh` in cache folder that uses already created cache files.
I had several issues depending on chosen options due to missing checks. After adding some of those checks it became more and more a blown up but buggy small copy of x11docker.
I have decided to drop this experimental code.

Rather it would make sense to check and improve x11docker code for faster startup. I already did that some monthes ago and was able to improve startup and shutdown time. Further improvement needs a deeper look at the codeflow whether somewhere can be spared a bit of time. As I already eliminated the most obvious brakes, this is not an easy task.

A `--fast` or `--skip` option does not help as there are not many checks that can be skipped.
