### ISSUE TITLE
Kill Docker container if x11 window was closed 

### ISSUE THREAD

**Issue by sandrokeil** [mviereck/x11docker#68]
I've encountered some issues, mostly with Chromium, that the Docker container is still running if I close the browser. Not all chromium processes are killed on closing the Browser.

Is it possible to check, if the x11 window/session was closed and the Docker container is still running? Does it makes sense to kill the Docker container if no x11 session exists anymore?

**Comment by mviereck** [comment]
x11docker already terminates docker container if the additional X server is closed. Also, the X server is terminated if the container terminates.

If chromium does not terminate itself on closed chromium window, I consider that a chromium bug. 
Windowed applications should terminate themself if their windows are closed.

If a process is still running with `--hostdisplay`, I see no way to decide if x11docker should terminate the container. For other X server options x11docker could check e.g. the output of `xwininfo -root -children` if there is any open window. But a process may close all windows and open another one after a pause. x11docker should not decide to terminate X only because the container currently does not obviously use it.

If you run chromium e.g. with `--weston-xwayland`, x11docker will terminate it if you close the weston window.

**Comment by mviereck** [comment]
x11docker has a new option `--checkwindow` that adresses this issue:
```
     --checkwindow [=ARG]  Run container until all X windows are closed.
                       If ARG is provided, run container as long as 'grep' can
                       find ARG in output of 'xwininfo -root -children'.
                       This option helps to keep alive containers with
                       self-forking applications like gnome-terminal
                       or to stop endless running ones like chromium.
```
With additional X servers it is enough to just set `--checkwindow`.
In your case using `--hostdisplay` with `chromium` something like `--checkwindow=Chromium` should work, if keyword `Chromium` appears in all chromium windows.
