### ISSUE TITLE
Plans to adapt to macOS?

### ISSUE THREAD

**Issue by InnovativeInventor** [mviereck/x11docker#94]
Any plans to get this on homebrew?

**Comment by mviereck** [comment]
x11docker is not adapted to macOS yet. Though, it would be possible.

Apple does not provide a developer VM with macOS like Microsoft does with win10. So I would need to have a macbook for development and further maintenance. So far I am not willingly to spend money on a macbook that I don't need otherwise.

However, you can already run x11docker in a Linux VM.

**Comment by InnovativeInventor** [comment]
I saw this some time ago: https://www.howtogeek.com/289594/how-to-install-macos-sierra-in-virtualbox-on-windows-10/

Also, have you heard of macstadium?

Btw, this project is amazing!

**Comment by mviereck** [comment]
> Btw, this project is amazing!

Thank you! :-)

> I saw this some time ago: https://www.howtogeek.com/289594/how-to-install-macos-sierra-in-virtualbox-on-windows-10/

I've already seen this and similar sites that provide hacks to somehow get macOS into a VM. I even downloaded a possibly illegal VM. It did not work. I decided not to spend more time on those hacks.

> Also, have you heard of macstadium?

I've looked at it. Quite expensive, would be enough to buy an old Mac. And 24 hours free trial are not enough to do anything useful.

Sorry, the only way I see is a physical macbook. Adapting x11docker to win10 in a VM was a PITA already. x11docker on win10 misses some features that might be possible if win10 wouldn't be that cruelsome slow in a VM and stopped me from investigating further. I don't wont to repeat a similar workaround way with macOS.

If you or someone else likes to spend me a macbook, I could just begin. ;-) Otherwise this has to wait until I have too much time and money simultuanously.
